import {
    LayoutDashboard,
    Users,
    UserCog,
    UserPlus,
    ClipboardList,
    Briefcase,
    CalendarDays,
    Lightbulb,
    CheckCircle,
    BookOpen,
    FileText,
    Settings,
    Shield,
    UsersRound,
    Award,
    User,
} from 'lucide-react';

export const menuConfig = [
    { label: 'Dashboard', path: '/dashboard', permission: null, icon: LayoutDashboard },
    {
        label: 'Master Data',
        permission: 'master-data.manage',
        icon: Users,
        children: [
            { label: 'Dosen', path: '/master-data/dosen', permission: 'master-data.manage' },
            { label: 'Mahasiswa', path: '/master-data/mahasiswa', permission: 'master-data.manage' },
            { label: 'Mitra', path: '/master-data/mitra', permission: 'master-data.manage' },
            { label: 'Periode Akademik', path: '/master-data/periode', permission: 'master-data.manage' },
            { label: 'Tema KP', path: '/master-data/tema', permission: 'master-data.manage' },
        ],
    },
    {
        label: 'Verifikasi Pendaftaran',
        path: '/kp/verifikasi',
        permission: 'kp.verifikasi-pendaftaran',
        icon: CheckCircle,
    },
    {
        label: 'Pendaftaran Kelompok',
        path: '/kp/kelompok',
        permission: 'kp.pendaftaran-kelompok',
        icon: UserPlus,
    },
    {
        label: 'Daftar Kelompok',
        path: '/kp/daftar-kelompok',
        permission: 'kp.plotting-dosen',
        icon: UsersRound,
    },
    {
        label: 'Logbook',
        path: '/kp/logbook',
        permission: 'kp.logbook',
        icon: BookOpen,
    },
    {
        label: 'Validasi Logbook',
        path: '/kp/logbook/validasi',
        permission: 'kp.validasi-logbook',
        icon: ClipboardList,
    },
    {
        label: 'Laporan KP',
        path: '/kp/laporan',
        permission: 'kp.laporan',
        icon: FileText,
    },
    {
        label: 'Validasi Laporan',
        path: '/kp/laporan/validasi',
        permission: 'kp.validasi-laporan',
        icon: ClipboardList,
    },
    {
        label: 'Nilai KP',
        path: '/kp/nilai',
        permission: 'kp.nilai',
        icon: CheckCircle,
    },
    {
        label: 'Nilai Saya',
        path: '/kp/nilai-saya',
        permission: 'kp.nilai-saya',
        icon: Award,
    },
    {
        label: 'Manajemen Pengguna',
        path: '/users',
        permission: 'pengaturan.manage',
        icon: UserCog,
    },
    {
        label: 'Manajemen Peran',
        path: '/roles',
        permission: 'pengaturan.manage',
        icon: Shield,
    },
    {
        label: 'Repository',
        path: '/repository',
        permission: 'repository.publish',
        icon: Briefcase,
    },
        {
        label: 'Pengaturan',
        path: '/pengaturan',
        permission: 'pengaturan.manage',
        icon: Settings,
    },
];
